# Generated by Django 2.2 on 2020-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20200713_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Дата и время удаления'),
        ),
        migrations.AddField(
            model_name='animals',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Отметка об удалении'),
        ),
    ]
