# Generated by Django 2.2 on 2020-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20200714_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='special_signs',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Особые приметы'),
        ),
    ]
