# Generated by Django 2.2 on 2020-07-15 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20200715_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='arrive_date',
            field=models.DateField(default=datetime.date(2020, 7, 15), verbose_name='Дата прибытия в приют'),
        ),
    ]
