# Generated by Django 2.2 on 2020-07-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_auto_20200715_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='arrive_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата прибытия в приют'),
        ),
    ]
