# Generated by Django 2.2 on 2020-09-04 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_auto_20200715_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ['-created_at'], 'verbose_name': 'Постояльцы приюта', 'verbose_name_plural': 'Постояльцы приюта'},
        ),
        migrations.AlterField(
            model_name='animals',
            name='height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес'),
        ),
    ]
