# Generated by Django 2.2 on 2020-09-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shelter.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0008_auto_20200904_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='arrive_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[shelter.validators.gt_current_date_validator], verbose_name='Дата прибытия в приют'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='birth_date',
            field=models.DateField(null=True, validators=[shelter.validators.gt_current_date_validator], verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='ShelterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
