# Generated by Django 2.2 on 2020-09-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0009_auto_20200906_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelteruser',
            options={'ordering': ['user'], 'verbose_name': 'Дополнительная информация О пользователе', 'verbose_name_plural': 'Дополнительная информация О пользователе'},
        ),
        migrations.AlterModelTable(
            name='shelteruser',
            table='acits_user',
        ),
    ]
