# Generated by Django 2.2 on 2020-09-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_auto_20200906_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.CharField(max_length=100, verbose_name='Название приюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
                'db_table': 'acits_shelters',
            },
        ),
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ['-created_at'], 'verbose_name': 'Постоялец приюта', 'verbose_name_plural': 'Постояльцы приюта'},
        ),
        migrations.AlterModelOptions(
            name='shelteruser',
            options={'ordering': ['user'], 'verbose_name': 'Дополнительная информация о пользователе', 'verbose_name_plural': 'Дополнительная информация о пользователе'},
        ),
        migrations.AddField(
            model_name='shelteruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter', verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
