# Generated by Django 2.2 on 2020-09-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0012_shelter_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='shelter',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Shelter', to='shelter.Shelter', verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
