# Generated by Django 2.2 on 2020-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_auto_20200906_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
    ]
