# Generated by Django 2.2 on 2020-09-06 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0014_auto_20200906_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='shelter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter', verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='shelter.Shelter', verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
