# Generated by Django 2.2 on 2020-09-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0015_auto_20200906_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelterUser',
        ),
    ]
