# Generated by Django 2.2 on 2020-09-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0016_delete_shelteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter', verbose_name='Приют'),
        ),
    ]
